name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Swift 6
    - name: Install Swift 6
      uses: SwiftyLab/setup-swift@latest

    # Resolve dependencies
    - name: Resolve dependencies
      run: swift package resolve

    # Build the project
    - name: Build the project
      run: swift build

    # Run tests
    - name: Run tests
      run: swift test --enable-code-coverage

    # Upload code coverage (optional)
    - name: Upload Code Coverage
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: .build/debug/codecov/

